---
kind: pipeline
type: docker
name: Lint and build project

platform:
  os: linux
  arch: amd64

steps:
  - name: Lint project
    image: node:18
    commands:
      - yarn
      - yarn lint

  - name: Build project
    image: node:18
    commands:
      - yarn
      - yarn build

---
kind: pipeline
type: docker
name: Compile & publish docker image

platform:
  os: linux
  arch: amd64

steps:
  - name: Publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/planetposen-frontend
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags: latest

depends_on:
  - Lint and build project

trigger:
  branch:
    - main
    - ci/ghcr-publish
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: signature
hmac: 2578e80da0b7719a6d85be93b4a86803159ba7f320707607df9b579979c66e39

...
