---
kind: pipeline
type: docker
name: Lint and build project

platform:
  os: linux
  arch: amd64

steps:
  - name: Build project
    image: node:18
    commands:
      - yarn
      - yarn build

  - name: Lint project
    image: node:18
    commands:
      - yarn
      - yarn lint

---
kind: pipeline
type: docker
name: Compile docker image

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: node:18
    commands:
      - yarn
      - yarn build

  - name: Publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/planetposen-frontend
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags: latest

depends_on:
  - Lint and build project

trigger:
  branch:
    - main
    - ci/ghcr-publish
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: signature
hmac: eac31ba5baf0202b5920c39674cbb95767fe91e8ee36c773e2db78eee31e8879

...
